package pojo;
// Generated Oct 3, 2022 3:35:44 PM by Hibernate Tools 4.3.1



/**
 * TblBuku generated by hbm2java
 */
public class TblBuku  implements java.io.Serializable {


     private String idBuku;
     private String judul;
     private String penulisId;
     private String penerbitId;
     private String genreId;
     private String sinopsis;
     private double harga;
     private int stok;

    public TblBuku() {
    }

    public TblBuku(String idBuku, String judul, String penulisId, String penerbitId, String genreId, String sinopsis, double harga, int stok) {
       this.idBuku = idBuku;
       this.judul = judul;
       this.penulisId = penulisId;
       this.penerbitId = penerbitId;
       this.genreId = genreId;
       this.sinopsis = sinopsis;
       this.harga = harga;
       this.stok = stok;
    }
   
    public String getIdBuku() {
        return this.idBuku;
    }
    
    public void setIdBuku(String idBuku) {
        this.idBuku = idBuku;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getPenulisId() {
        return this.penulisId;
    }
    
    public void setPenulisId(String penulisId) {
        this.penulisId = penulisId;
    }
    public String getPenerbitId() {
        return this.penerbitId;
    }
    
    public void setPenerbitId(String penerbitId) {
        this.penerbitId = penerbitId;
    }
    public String getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(String genreId) {
        this.genreId = genreId;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public double getHarga() {
        return this.harga;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }




}


