package pojo;
// Generated Oct 3, 2022 3:35:44 PM by Hibernate Tools 4.3.1



/**
 * TblGenre generated by hbm2java
 */
public class TblGenre  implements java.io.Serializable {


     private String idGenre;
     private String nama;
     private String keterangan;

    public TblGenre() {
    }

    public TblGenre(String idGenre, String nama, String keterangan) {
       this.idGenre = idGenre;
       this.nama = nama;
       this.keterangan = keterangan;
    }
   
    public String getIdGenre() {
        return this.idGenre;
    }
    
    public void setIdGenre(String idGenre) {
        this.idGenre = idGenre;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }




}


