package pojo;
// Generated Oct 3, 2022 3:35:44 PM by Hibernate Tools 4.3.1



/**
 * TblPenulis generated by hbm2java
 */
public class TblPenulis  implements java.io.Serializable {


     private String idPenulis;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;

    public TblPenulis() {
    }

    public TblPenulis(String idPenulis, String nama, String alamat, String noTelp, String email) {
       this.idPenulis = idPenulis;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }
   
    public String getIdPenulis() {
        return this.idPenulis;
    }
    
    public void setIdPenulis(String idPenulis) {
        this.idPenulis = idPenulis;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


