package pojo;
// Generated Oct 3, 2022 3:35:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblTrx generated by hbm2java
 */
public class TblTrx  implements java.io.Serializable {


     private String idTrx;
     private Date tanggal;
     private String pelangganId;

    public TblTrx() {
    }

    public TblTrx(String idTrx, Date tanggal, String pelangganId) {
       this.idTrx = idTrx;
       this.tanggal = tanggal;
       this.pelangganId = pelangganId;
    }
   
    public String getIdTrx() {
        return this.idTrx;
    }
    
    public void setIdTrx(String idTrx) {
        this.idTrx = idTrx;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getPelangganId() {
        return this.pelangganId;
    }
    
    public void setPelangganId(String pelangganId) {
        this.pelangganId = pelangganId;
    }




}


